platform: linux/arm

clone:
  git:
    image: armswarmdrone/git

pipeline:
  build_rootfs:
    image: quay.io/armswarm/docker:latest
    environment:
      - REL=v3.6
    commands:
      - apk add --no-cache grep curl xz
      - ./mkimage-alpine.sh

  publish:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/alpine
    tag: [ "3.6", "latest" ]
    when:
      branch: master
      event: push

  notify:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
