platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  build_rootfs:
    image: quay.io/armswarm/alpine:3.6
    environment:
      - REL=v3.7
    commands:
      - apk add --no-cache grep curl xz
      - ./mkimage-alpine.sh

  publish:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_username, docker_password, docker_registry ]
    repo: quay.io/armswarm/alpine
    tag: [ "3.7", "latest" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
