clone:
  git:
    image: armswarmdrone/git

pipeline:
  build:
    image: quay.io/armswarm/docker:latest
    environment:
      - REL=v3.5
    commands:
      - apk add --no-cache grep curl xz
      - ./mkimage-alpine.sh

  docker:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/alpine
    tag: [ "3.5", "latest" ]
    when:
      branch: master
      event: push

  slack:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
