pipeline:
  build:
    image: quay.io/armswarm/docker:latest
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - apk add --no-cache grep curl
      - ./mkimage-alpine.sh

services:
  docker:
    image: quay.io/armswarm/docker:dind
    command: []
    privileged: true
